# fly.toml app configuration file generated for h5p-minimal on 2025-07-13T23:39:06+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'h5p-minimal'
primary_region = 'sjc'

[build]
  dockerfile = './Dockerfile'

# [deploy]
#   release_command = 'npm run migrate:prod'

[env]
  NODE_ENV = 'production'
  PORT = '3001'

[processes]
  app = 'npm start'

[[mounts]]
  source = 'h5p_data'
  destination = '/app/data'
  initial_size = '10gb'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '30s'
    method = 'GET'
    path = '/api/projects/health'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048
