# fly.toml app configuration file for h5p-minimal (no-db version)
app = 'h5p-minimal'
primary_region = 'sjc'

[build]
  dockerfile = './Dockerfile.no-db'

[env]
  NODE_ENV = 'production'
  PORT = '3001'
  SKIP_DB = 'true'
  SKIP_DB_CONNECTION = 'true'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = false
  min_machines_running = 1
  
  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/api/health"

[[mounts]]
  source = 'h5p_data'
  destination = '/app/data'
  initial_size = '1gb'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '30s'
    method = 'GET'
    path = '/api/projects/health'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048
