/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "wgawvunfjjjywpywuvqf"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndnYXd2dW5mampqeXdweXd1dnFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM2NDc5NDMsImV4cCI6MjA4OTIyMzk0M30.kIWKvOpuCcOqA5ry8dSCyQysCS-VyTORhATR93-Qyeo"